
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jadphaypzbsxofowrjvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImphZHBoYXlwemJzeG9mb3dyanZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MTc4MjMsImV4cCI6MjA2MzQ5MzgyM30.YiP_KbzmfCn7lnE3lxrZ-FxKpHRFRAPQJMDgRvIlsN4";

// Create clean Supabase client without aggressive cache-busting
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  db: {
    schema: 'public'
  },
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  },
  realtime: {
    params: {
      eventsPerSecond: 10
    }
  }
});
